name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --locked --workspace --verbose
      - name: Build (no default features)
        run: cargo build --locked --workspace --verbose --no-default-features
      - name: Build WASM
        run: cargo build --verbose --target wasm32-unknown-unknown --no-default-features --features="browser"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1

      - name: Run tests
        run: cargo test --locked --workspace --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1

      - name: Rustfmt
        run: cargo +nightly fmt --all -- --check

      - name: Clippy
        run: cargo clippy --tests --workspace -- -D warnings
